// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQjAv5lin1oKI_VfT6a2Z0VL234eaVToM',
    appId: '1:532890963327:web:85fcfdbcc1a021caccde4a',
    messagingSenderId: '532890963327',
    projectId: 'mynotes-3badf',
    authDomain: 'mynotes-3badf.firebaseapp.com',
    databaseURL: 'https://mynotes-3badf-default-rtdb.firebaseio.com',
    storageBucket: 'mynotes-3badf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiqnwLHxvBlMLtDLvNL8U7IIjF67WM6cE',
    appId: '1:532890963327:android:d6114c494a73e740ccde4a',
    messagingSenderId: '532890963327',
    projectId: 'mynotes-3badf',
    databaseURL: 'https://mynotes-3badf-default-rtdb.firebaseio.com',
    storageBucket: 'mynotes-3badf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfsaRqK5aLu9Jsup6Pq0xI3J1GUr9v7D0',
    appId: '1:532890963327:ios:cf55f4a2a92831ebccde4a',
    messagingSenderId: '532890963327',
    projectId: 'mynotes-3badf',
    databaseURL: 'https://mynotes-3badf-default-rtdb.firebaseio.com',
    storageBucket: 'mynotes-3badf.appspot.com',
    iosClientId:
        '532890963327-5052uq43cksqm1cq2hroj3u6ipqttfb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfsaRqK5aLu9Jsup6Pq0xI3J1GUr9v7D0',
    appId: '1:532890963327:ios:cf55f4a2a92831ebccde4a',
    messagingSenderId: '532890963327',
    projectId: 'mynotes-3badf',
    databaseURL: 'https://mynotes-3badf-default-rtdb.firebaseio.com',
    storageBucket: 'mynotes-3badf.appspot.com',
    iosClientId:
        '532890963327-5052uq43cksqm1cq2hroj3u6ipqttfb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: "AIzaSyAQjAv5lin1oKI_VfT6a2Z0VL234eaVToM",
  //   authDomain: "mynotes-3badf.firebaseapp.com",
  //   databaseURL: "https://mynotes-3badf-default-rtdb.firebaseio.com",
  //   projectId: "mynotes-3badf",
  //   storageBucket: "mynotes-3badf.appspot.com",
  //   messagingSenderId: "532890963327",
  //   appId: "1:532890963327:web:85fcfdbcc1a021caccde4a",
  // );
}
